### ISSUE TITLE
Investigate 403 from AWS

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#127]
Getting 403 FORBIDDEN response from aws, even though the credentials are valid.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/Action_308be6b2-139f-4109-854c-8be86cd124e4.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/Action_308be6b2-139f-4109-854c-8be86cd124e4.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/Action_4f551960-a9af-425b-822d-656808d27ab5.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/Action_4f551960-a9af-425b-822d-656808d27ab5.log) for details.

**Comment by amihaiemil** [comment]
@rultor hello

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil only the repository's owner can trigger an index action.

If the repository is under an organization you must be an active admin and **I must be a member** (this is because currently I cannot check your membership otherwise - see [here](https://developer.github.com/v3/orgs/members/#get-organization-membership)).

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil only the repository's owner can trigger an index action.

If the repository is under an organization you must be an active admin and **I must be a member** (this is because currently I cannot check your membership otherwise - see [here](https://developer.github.com/v3/orgs/members/#get-organization-membership)).
