### ISSUE TITLE
Agent won't take command from admin

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#136]
[Here](https://github.com/opencharles/charles-github-ejb/issues/127#issuecomment-260676411), the agent won't take an index command even though the commander is an active admin and the agent is member of the organization.

Investigate, fix the bug and add the logs link to the denial response.

**Comment by amihaiemil** [comment]
@charlesmike index pls

**Comment by charlesmike** [comment]
> @charlesmike index pls

@amihaiemil only the repository's owner can trigger an index action.

If the repository is under an organization you must be an active admin and **I must be a member** (this is because currently I cannot check your membership otherwise - see [here](https://developer.github.com/v3/orgs/members/#get-organization-membership)).
