### ISSUE TITLE
Implement sitemap.xml crawling

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#145]
Implement command to crawl sitemap.xml

**Comment by amihaiemil** [comment]
Postponed

**Comment by amihaiemil** [comment]
@charlesmike delete

**Comment by charlesmike** [comment]
> @charlesmike delete

@amihaiemil the repository's name in a delete command has to be between single back apostrophes.
and it has to match the actual reponame exactly (case sensitive) 

A valid delete command here is ``@charlesmike delete `charles-rest` index``.

**Comment by amihaiemil** [comment]
@charlesmike delete `charles-rest` index

**Comment by charlesmike** [comment]
> @charlesmike delete `charles-rest` index

@amihaiemil the `charles-rest` index was successfully deleted. 
Don't forget to remove the script form your website since the search will not work anymore.
See [logs](http://charles.amihaiemil.com/logs.html?log=/78b229e6-0df9-4c02-b49d-0878a4412d68.log) for details.

If you can spare a minute, please consider opening an issue [here](https://github.com/opencharles/charles-rest/issues/new),let us know why you stopped using this service, what you didn't like and what we could improve. Thanks!

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/eb7ff9dc-7cc2-4a8d-8e81-77ef04c9871e.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/eb7ff9dc-7cc2-4a8d-8e81-77ef04c9871e.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html#commands).

**Comment by amihaiemil** [comment]
@charlesmike delete `opencharles/charles-rest` index

**Comment by charlesmike** [comment]
> @charlesmike delete `opencharles/charles-rest` index

@amihaiemil the repository's name in a delete command has to be between single back apostrophes.
and it has to match the actual reponame exactly (case sensitive) 

A valid delete command here is ``@charlesmike delete `charles-rest` index``.

**Comment by amihaiemil** [comment]
@charlesmike delete `charles-rest` index

**Comment by charlesmike** [comment]
> @charlesmike delete `charles-rest` index

@amihaiemil the `charles-rest` index was successfully deleted. 
Don't forget to remove the script form your website since the search will not work anymore.
See [logs](http://charles.amihaiemil.com/logs.html?log=/211e1304-fa11-4c31-a330-f6c19e88147d.log) for details.

If you can spare a minute, please consider opening an issue [here](https://github.com/opencharles/charles-rest/issues/new),let us know why you stopped using this service, what you didn't like and what we could improve. Thanks!

**Comment by amihaiemil** [comment]
@charlesmike index site pls

**Comment by charlesmike** [comment]
> @charlesmike index site pls

@amihaiemil sorry I do not understand you. See [this link](http://charles.amihaiemil.com/doc.html#commands) for more details.

**Comment by amihaiemil** [comment]
@charlesmike index site

**Comment by charlesmike** [comment]
> @charlesmike index site

@amihaiemil sorry I do not understand you. See [this link](http://charles.amihaiemil.com/doc.html#commands) for more details.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/8dac68bd-5e77-418f-90b5-1073725b6284.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/8dac68bd-5e77-418f-90b5-1073725b6284.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
search script added: 376d87d

**Comment by amihaiemil** [comment]
@charlesmike delete `charles-rest` index

**Comment by charlesmike** [comment]
> @charlesmike delete `charles-rest` index

@amihaiemil the `charles-rest` index was successfully deleted. 
Don't forget to remove the script form your website since the search will not work anymore.
See [logs](http://charles.amihaiemil.com/logs.html?log=/be03920a-882e-4095-9e0b-94ba04048edb.log) for details.

If you can spare a minute, please consider opening an issue [here](https://github.com/opencharles/charles-rest/issues/new),let us know why you stopped using this service, what you didn't like and what we could improve. Thanks!

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/0919bee6-8763-4dfe-82d1-ef7de46d9d1a.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/0919bee6-8763-4dfe-82d1-ef7de46d9d1a.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello there

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html#commands).

**Comment by amihaiemil** [comment]
@charlesmike delete `opencharles/charles-rest` index please

**Comment by amihaiemil** [comment]
@charlesmike hi

**Comment by charlesmike** [comment]
> @charlesmike delete `opencharles/charles-rest` index please

@amihaiemil the repository's name in a delete command has to be between single back apostrophes.
and it has to match the actual reponame exactly (case sensitive) 

A valid delete command here is ``@charlesmike delete `charles-rest` index``.

**Comment by amihaiemil** [comment]
@charlesmike delete `charles-rest` index will you

**Comment by charlesmike** [comment]
> @charlesmike delete `charles-rest` index will you

@amihaiemil the `charles-rest` index was successfully deleted. 
Don't forget to remove the script form your website since the search will not work anymore.
See [logs](http://charles.amihaiemil.com/logs.html?log=/101c34d6-94da-4e8d-8557-8bdc1b4864b7.log) for details.

If you can spare a minute, please consider opening an issue [here](https://github.com/opencharles/charles-rest/issues/new),let us know why you stopped using this service, what you didn't like and what we could improve. Thanks!

**Comment by amihaiemil** [comment]
@charlesmike try to index this site please

**Comment by charlesmike** [comment]
> @charlesmike try to index this site please

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/2c5d71d5-e07c-4ea7-9f82-44599ca6881f.log).

**Comment by charlesmike** [comment]
> @charlesmike try to index this site please

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/2c5d71d5-e07c-4ea7-9f82-44599ca6881f.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike hello there!

**Comment by charlesmike** [comment]
> @charlesmike hello there!

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html#commands).

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html#commands).

**Comment by amihaiemil** [comment]
@charlesmike try to index [this](http://amihaiemil.github.io/sitemap.xml) sitemap pls

**Comment by charlesmike** [comment]
> @charlesmike try to index [this](http://amihaiemil.github.io/sitemap.xml) sitemap pls

@amihaiemil the given page or sitemap does not seem to belong to the website hosted in this repo!

Make sure that the link starts with ``http://`` or ``https://`` followed by``yourusername.github.io/...``. Do not use the CNAME or any other domain, even if it redirects toa page from this repo. Also, make sure that the link is specified in Markdown format. 

 If this condition is met and it still doesn't work please open an issue [here](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
done
