### ISSUE TITLE
AWS Forbidden again

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#162]
Check [this](http://charles.amihaiemil.com/logs.html?log=/e6c3b008-4be2-4dad-879e-99e4068f8292.log) and fix the issue

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/dcc7368b-7629-4f15-81df-417e5736a690.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Index command executed successfully! 
 Add the following script to the website in order to make the search functionality available:

 &lt;script src=&quot;#&quot;&gt;charles-rest&lt;/script&gt; 

 See [logs](http://charles.amihaiemil.com/logs.html?log=/dcc7368b-7629-4f15-81df-417e5736a690.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
done in #165
