### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by salikjan** [amihaiemil/charles-github-ejb#167]
@charlesmike hi there

**Comment by amihaiemil** [comment]
@salikjan nice to see you around.

The bot wont answer to that because I accidentally opened the notification email on my phone. And when that mail is opened, Github marks the notification as "read" - so when the 2 minutes expire and the bot does the check, it wont see it.

Also, keep this issue open, I'll explain here and also answer your questions sometime today when I get the time.

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html#commands).

**Comment by amihaiemil** [comment]
@salikjan First, to answer your questions:

> do I have to use rultor?

No, rultor is a chatbot that we command solely on Github, nothing to do locally about it. When a PR will pass code-review, I will ask rultor to merge it. You'll see, it's quite a cool thing!

> I use windows, not unix

Shouldn't be a problem, if you receive an issue that cannot be done on windows, simply let it to someone else.

> mvn clean install failed tests

Well, there isn't much I can tell you just from that. Look in the logs, it should tell you which test fails and you can figure out why from there. Please, open an Issue about it if it's a bug or you cannot figure out the problem, but add the full logs.

> pom.xml plugin issue

Also here, I cannot tell much - it should be able to fetch all of its dependencies from maven central. Check your connection, if you are by any chance behind a proxy etc.

**Comment by amihaiemil** [comment]
@salikjan Second, you have to **fork** the repo you want to contribute to - then you will have a copy of it under your name and that is the one that you **clone** locally.

There will be this triangle of repos: the original one, the fork under your name and the one you have locally on your machine. You work on a separate branch named after the ticket number (e.g. ticket number is 123 => branch name is 123). When you're done, make a PR.

Does this make sense, do you know github enough to understand what I mean? If not, ask me or follow a Github tutorial, it's one of the most basic flows of working around here :)

**Comment by amihaiemil** [comment]
@salikjan Lastly, I don't think charles-rest is a good option to start with. For a couple of reasons:

1) It's better to have a fresh project so we all see best what is expected, what's the coding style etc. If we start directly on an ongoing project it's much harder because it already has its architecture and bugs that need to be solved etc. It would be quite frustrating to learn on it, that's what I think :D 

2) This project in particular I will try to release soon so I don't think there'll be any significant implementation in the next few weeks/next month.

3) It's a lot easier to learn the concepts and unit testing when you have seen the project developing from the start.

As I wrote in an article, I have in mind a library that parses YAML format, which I would use in this project as well - in a future version I would like to have a .yml configuration file, for instance.


Also, you can checkout [charles](https://www.github.com/opencharles/charles) or [eva](https://www.github.com/amihaiemil/eva) - those are also libraries, so easier to start contributing on.

What do you think?

**Comment by salikjan** [comment]
@amihaiemil please tell me what do you mean by fork? Create new branch by git checkout and after that make any changes in that branch and push changes NOT to master but to newly created branch?
If yes then I realize the process of developing in git. At least i read a lot about it. And used it when was solving issues from codeeval.com.

@amihaiemil at first i've choosen eva. i always wanted to have expirience in AI but didn't read too much about it.
Also i googled about YAML. It interesting to me too. It's a great expirience to resemble parsing. I use simple regular expressions almost every day in my work. So it'l be great.

**Comment by amihaiemil** [comment]
@salikjan cool, good to know you like the idea :) 
I'll make a repo for the project and let you know in a few minutes, I'll tag you in an issue there.
