### ISSUE TITLE
Bug: Misstyped keyword in comparison in CommandCategory

### ISSUE THREAD

**Issue by salikjan** [amihaiemil/charles-github-ejb#181]
Code snipppet:
```
public boolean isUnderstood() {
        return !this.type.equals("unkown");
}
```
Method isUnderstood() is never used but for future purposes must be corrected.
Should be:
```
return !this.type.equals("unknown");
```

**Comment by amihaiemil** [comment]
@salikjan The method is actually used in only one place, inside ``Brain.categorizeCommand()``. Its purpose is to stop the language iterations, in order to avoid useless loops once the command has been understood. 

The idea is, the Brain has an array of Language and once a command is received, it iterates over the languages and tries to "understand" the command. Once it's understood, it makes no sense to look over the next languages.

**Comment by amihaiemil** [comment]
@salikjan By the way, when you are copying code snippets and such things in a comment, you can use [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) to style your comment and make it more readable.

E.g.
public boolean isUnderstood() {
return !this.type.equals("unkown");
}

vs

```
public boolean isUnderstood() {
   return !this.type.equals("unkown");
}
```

You can style a code snippet by adding 3 back-apostrophes (`` ``` ``) on the first line before the code, and first line after it.

**Comment by salikjan** [comment]
@amihaiemil modified code snippet. understood about isUnderstood() method
