### ISSUE TITLE
SystemProperty.java:33-35: Implement and Unit test 4 system...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/charles-github-ejb#201]
The puzzle `199-aff84e88` in [`src/main/java/com/amihaiemil/charles/aws/SystemProperty.java`](https://github.com/opencharles/charles-rest/blob/master/src/main/java/com/amihaiemil/charles/aws/SystemProperty.java) (lines 33-35) has to be resolved: Implement and Unit test 4 system properties SecretKey, Region, EsEndPoint and AccessKeyId. Also add fake implementation for the interfaces to use them in testing.

The puzzle was created by sherif on 19-Mar-17. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by amihaiemil** [comment]
@SherifWaly Want to do this? I would do as follows: 

* class ``AbstractSystemProperty`` implements ``SystemProperty``, which has a String attribute, ``name``.
 In the ``read()`` method you simply have ``System.getProperty(this.name)``
* the classes for each of the 4 interfaces implement the respective interface and extend ``AbstractSystemProperty``

e.g. for ``Region``:

```
/**
 * Region as a system property.
 */
public final class StRegion implements Region extends AbstractSystemProperty {
    public StRegion(final String name) {
        super(name);
    }
}
```

As I explained in the [article](http://www.amihaiemil.com/2017/02/24/each-system-property-a-class.html) these classes cannot really be unit tested, since we end up with the same problem we're trying to avoid :) 

And I would add a puzzle, with ``15min`` estimation, for adding of the ``Fake`` implementations in each of the 4 interfaces.

What do you think? :D

**Comment by SherifWaly** [comment]
@amihaiemil Ok, I will try to do it :D 
Just to make sure the unit testing would be made for the `Fake` implementations not the real ones, is that right :D?

**Comment by amihaiemil** [comment]
@SherifWaly yes :D

**Comment by 0pdd** [comment]
The puzzle `199-aff84e88` has disappeared from the source code, that's why I closed this issue.
