### ISSUE TITLE
Fix rultor merge

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#213]
Rultor merge keeps failing on a test: https://github.com/opencharles/charles-rest/pull/212#issuecomment-309498119

**Comment by amihaiemil** [comment]
@charlesmike hello, are you there?

**Comment by charlesmike** [comment]
> @charlesmike hello, are you there?

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html#commands).
Also, [this](http://www.amihaiemil.com/2017/05/23/meet-charles-michael.html) blog post might be useful.

**Comment by amihaiemil** [comment]
@charlesmike delete `charles-rest` index pls

**Comment by charlesmike** [comment]
> @charlesmike delete `charles-rest` index pls

@amihaiemil the `charles-rest` index was successfully deleted. 
Don't forget to remove the script form your website since the search will not work anymore.
See [logs](http://charles.amihaiemil.com/logs.html?log=/1b19616e-30e8-4f4a-90af-37b1bfa884ef.log) for details.

If you can spare a minute, please consider opening an issue [here](https://github.com/opencharles/charles-rest/issues/new),let us know why you stopped using this service, what you didn't like and what we could improve. Thanks!

**Comment by amihaiemil** [comment]
@charlesmike index the new site pls

**Comment by charlesmike** [comment]
> @charlesmike index the new site pls

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/c9bb2e7b-734c-41ab-9673-2298527e074c.log).

**Comment by charlesmike** [comment]
> @charlesmike index the new site pls

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/c9bb2e7b-734c-41ab-9673-2298527e074c.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
fixed here: https://github.com/opencharles/charles-rest/pull/231#event-1198728248
