### ISSUE TITLE
Tweet.java:39-40: Pull out the system proerties, same...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/charles-github-ejb#243]
The puzzle `241-12bd8c89` (from #241) in [`src/main/java/com/amihaiemil/charles/github/Tweet.java`](https://github.com/opencharles/charles-rest/blob/master/src/main/java/com/amihaiemil/charles/github/Tweet.java) (lines 39-40) has to be resolved: "Pull out the system proerties, same as was done in the aws layer, to simplify the unit tests."

The puzzle was created by amihaiemil on 17-Aug-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://opencharles.github.io/charles-rest/config.html) new page please

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://opencharles.github.io/charles-rest/config.html) new page please

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/180c9c64-3d98-4d57-804e-b03331f1196c.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://opencharles.github.io/charles-rest/config.html) new page please

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/180c9c64-3d98-4d57-804e-b03331f1196c.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by 0pdd** [comment]
The puzzle `241-12bd8c89` has disappeared from the source code, that's why I closed this issue.
