### ISSUE TITLE
Implement IndexPage.perform

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#91]
IndexPage Step needs to be implemented

**Comment by amihaiemil** [comment]
@charlesmike hi

**Comment by charlesmike** [comment]
> @charlesmike hi

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format `owner.github.io` (or has a `gh-pages` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly.

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Index command executed successfully! 
 Add the following script to the website in order to make the search functionality available:

 &lt;script src=&quot;#&quot;&gt;charles-github-ejb&lt;/script&gt; 

 See [logs](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/7a27979c-d5a0-4429-9602-eadbb2087d81.log) for more details. 
 If you notice any inexplicable errors, please open an issue <a href="https://github.com/amihaiemil/charles-github-ejb">here</a>

**Comment by amihaiemil** [comment]
@charlesmike hi

**Comment by charlesmike** [comment]
> @charlesmike hi

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format `owner.github.io` (or has a `gh-pages` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
done
