### ISSUE TITLE
Implement AmazonEsRepository

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#92]
Amazon ElasticSearch repository which uses the Amazon Java SDK to send requests to the elasticsearch hosted in the AWS cloud. This leverages the request signing process; it would be more difficult to implement it with the raw Apache Http client.

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
@charlesmike index plm

**Comment by charlesmike** [comment]
> @charlesmike index pls

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly.

**Comment by charlesmike** [comment]
> @charlesmike index pls

@amihaiemil Index command executed successfully! 
 Add the following script to the website in order to make the search functionality available:

 &lt;script src=&quot;#&quot;&gt;charles-github-ejb&lt;/script&gt; 

 See [logs](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/94e77037-36bf-4ff2-b00c-8156a99fb54e.log) for more details. 
 If you notice any inexplicable errors, please open an issue <a href="https://github.com/amihaiemil/charles-github-ejb">here</a>

**Comment by amihaiemil** [comment]
@charlesmike index [this](#) page

**Comment by charlesmike** [comment]
> @charlesmike index [this](#) page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly.

**Comment by charlesmike** [comment]
> @charlesmike index [this](#) page

@amihaiemil Index command executed successfully! 
 Add the following script to the website in order to make the search functionality available:

 &lt;script src=&quot;#&quot;&gt;charles-github-ejb&lt;/script&gt; 

 See [logs](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/892a0b08-cbf9-4fb9-ae1b-06631af1f779.log) for more details. 
 If you notice any inexplicable errors, please open an issue <a href="https://github.com/amihaiemil/charles-github-ejb">here</a>

**Comment by amihaiemil** [comment]
@charlesmike how is it up on aws??

**Comment by charlesmike** [comment]
> @charlesmike how is it up on aws??

@amihaiemil sorry I do not understand you. See [this link](http://charles.amihaiemil.com/doc.html#commands) for more details.

**Comment by amihaiemil** [comment]
@charlesmike index please

**Comment by charlesmike** [comment]
> @charlesmike index please

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly.

**Comment by charlesmike** [comment]
> @charlesmike index please

@amihaiemil Index command executed successfully! 
 Add the following script to the website in order to make the search functionality available:

 &lt;script src=&quot;#&quot;&gt;charles-github-ejb&lt;/script&gt; 

 See [logs](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/4883dc70-cc94-404d-a347-34c8bfe4b94c.log) for more details. 
 If you notice any inexplicable errors, please open an issue <a href="https://github.com/amihaiemil/charles-github-ejb">here</a>

**Comment by amihaiemil** [comment]
@charlesmike hi there!!!

**Comment by charlesmike** [comment]
> @charlesmike hi there!!!

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format `owner.github.io` (or has a `gh-pages` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
Done
